### ISSUE TITLE
TitleBar问题

### ISSUE THREAD

**Issue by jueduiyheng** [HHotHeart/MVPArch#1]
TitleDemoActivity 里面的
TitleBar 背景颜色///右边图片设置都无效

 return new TitleParam("Title Ddddemo")
                .setTittleBarBgColor(ColorUtils.getColor(R.color.colorPrimaryDark))
                .setLeftIcon(R.drawable.ic_mvparch_arrow_back_white)
                .setRightIcon(R.mipmap.ic_right_img)
                .setRightText("完成")
                .setMiddleTextColor(Color.WHITE);

**Comment by huangxiaolianghh** [comment]
感谢issue，已修复并发布beta新版1.0.8-beta.6
